parameters:
#    liber_user.example.class: Liber\UserBundle\Example

services:
#    liber_user.example:
#        class: %liber_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
