liber_beleggers_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: LiberBeleggersBundle:Default:index }

liber_beleggers_stock_overview:
    pattern: /stock/overview
    defaults: { _controller: LiberBeleggersBundle:Stock:overview }