liber_beleggers_homepage:
    pattern:  /{name}
    defaults: { _controller: LiberBeleggersBundle:Default:index }

liber_beleggers_stock_overview:
    pattern: /stock/overview
    defaults: { _controller: LiberBeleggersBundle:Stock:overview }

liber_beleggers_stock_edit:
    pattern: /stock/edit
    defaults: { _controller: LiberBeleggersBundle:Stock:edit }