liber_beleggers_settings:
    pattern:  /settings/
    defaults: { _controller: LiberBeleggersBundle:Settings:overview }

liber_beleggers_settings_overview:
    pattern: /settings/overview
    defaults: { _controller: LiberBeleggersBundle:Settings:overview }

liber_beleggers_settings_edit:
    pattern: /settings/edit
    defaults: { _controller: LiberBeleggersBundle:Settings:edit }

liber_beleggers_settings_edit_types:
    pattern: /settings/editTypes
    defaults: { _controller: LiberBeleggersBundle:Settings:editTypes }

liber_beleggers_cashier_register:
    pattern: /cashier/register
    defaults: { _controller: LiberBeleggersBundle:Cashier:order }