parameters:
#    liber_beleggers.example.class: Liber\BeleggersBundle\Example

services:
#    liber_beleggers.example:
#        class: %liber_beleggers.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
