# src/Liber/BeleggersBundle/Resources/config/doctrine/GlobalSettings.orm.yml
Liber\BeleggersBundle\Entity\GlobalSettings:
    type:  entity
    table: globalSettings

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        currency:
            type: string
            length: 255
        unitPrice:
            type: decimal
            precision: 4
            scale: 2
            nullable: true
        unitName:
            type: string
            length: 255
            nullable: true

    manyToOne:
        user:
            targetEntity: Liber\UserBundle\Entity\User