# src/Liber/BeleggersBundle/Resources/config/doctrine/StockType.orm.yml
Liber\BeleggersBundle\Entity\StockType:
    type:  entity
    table: stockType

    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 255

    oneToMany:
        stocks:
            targetEntity: Stock
            mappedBy: stockType
