parameters:
#    SpiritStock_user.example.class: SpiritStock\UserBundle\Example

services:
#    SpiritStock_user.example:
#        class: %SpiritStock_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
