<?php

namespace SpiritStock\StockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    public function inverseFindToBeUpdatedByIdsAndUser($ids, $user) {
        $time = new \DateTime('-5 minutes');
        $time->format('c');

        $ids = implode(',', $ids);

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('s')
           ->from('SpiritStock\StockBundle\Entity\Stock', 's')
           ->andWhere($qb->expr()->notIn('s.id', ':ids'))
           ->andWhere('s.updated <= :time')
           ->andWhere('s.user = :user')
           ->setParameters(array(
                    'ids' => $ids,
                    'time'=> $time,
                    'user'=> $user,
                )
            );
        return $qb->getQuery()->execute();
    }

}
