<?php

namespace SpiritStock\StockBundle\Repository;

use Doctrine\ORM\EntityRepository;
use SpiritStock\StockBundle\Entity\Stock;
use SpiritStock\UserBundle\Entity\User;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    /**
     * Gets all entities not referred to in ID array
     *
     * @param array $ids
     * @param User  $user
     *
     * @return Stock[]
     */
    public function inverseFindToBeUpdatedByIdsAndUser($ids, $user) {
        $qb   = $this->getEntityManager()->createQueryBuilder();
        $ids  = implode(',', $ids);
        $time = new \DateTime('-5 minutes');

        $time->format('c');

        $qb->select('s')
           ->from('SpiritStock\StockBundle\Entity\Stock', 's')
           ->andWhere($qb->expr()->notIn('s.id', ':ids'))
           ->andWhere('s.updated <= :time')
           ->andWhere('s.user = :user')
           ->setParameters(array(
                    'ids' => $ids,
                    'time'=> $time,
                    'user'=> $user,
                )
            );

        return $qb->getQuery()->execute();
    }
}
