parameters:
#    spiritstock_stock.example.class: SpiritStock\StockBundle\Example

services:
    stock.twig.round_to_unit_extension:
        class: SpiritStock\StockBundle\Twig\RoundToUnitExtension
        tags:
            - { name: twig.extension }

    stock.service.stock_service:
        class: SpiritStock\StockBundle\Service\StockService
        arguments: ["@doctrine.orm.entity_manager"]

    stock.service.history_service:
        class: SpiritStock\StockBundle\Service\HistoryService
        arguments: ["@doctrine.orm.entity_manager"]